name: Build and Test PyKaldi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
        
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install virtualenv
        python -m virtualenv pykaldi_env
        pykaldi_env/bin/python3 -m pip install numpy pyparsing ninja wheel
        # Kaldi dependencies
        sudo apt-get install sox
    - name: Check dependencies
      run: |
        source pykaldi_env/bin/activate
        cd tools
        ./check_dependencies.sh
    - name: Build protobuf
      run: |
        source pykaldi_env/bin/activate
        cd tools
        ./install_protobuf.sh
    - name: Build clif
      run: |
        source pykaldi_env/bin/activate
        cd tools
        ./install_clif.sh
    - name: Build kaldi
      run: |
        source pykaldi_env/bin/activate
        cd tools
        git clone -b pykaldi_02 https://github.com/pykaldi/kaldi.git
        cd kaldi/tools
        git pull
        cd extras
        sudo ./install_mkl.sh
        cd ../../..
        ./install_kaldi.sh
    - name: Build PyKaldi
      run: |
        source pykaldi_env/bin/activate
        python3 setup.py install
    - name: Test PyKaldi
      run: |
        source pykaldi_env/bin/activate
        python3 setup.py test
        
